config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include('users.urls')),
    path('', include('tasks.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path

from .views import *

app_name = 'tasks'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('task/<int:pk>', TaskUpdateView.as_view(), name='update_task'),
    path('efficiency/<str:group_name>', efficiency_view, name='efficiency'),

    path('api/user_tasks/<int:days>/', get_user_tasks, name='user_tasks'),
    path('api/division_tasks/<int:days>/', get_all_division_tasks, name='division_tasks'),
    path('api/task_list/', TaskApiView.as_view(), name='task_api')
]

users/urls.py
from django.urls import path, include

from .views import (
    LoginView, DivisionView, PasswordResetView, PasswordResetConfirmView, UpdateEmployeeView, CreateEmployeeView,
    password_change, delete_employee,
)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('password_change/<int:pk>/', password_change, name='password_change'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('', include('django.contrib.auth.urls')),

    path('delete/<int:pk>/', delete_employee, name='delete_employee'),
    path('update/<int:pk>/', UpdateEmployeeView.as_view(), name='update_employee'),
    path('add_employee/', CreateEmployeeView.as_view(), name='create_employee'),
    path('division/', DivisionView.as_view(), name='division'),
]

templates/src/_footer.html
<footer>
  <!-- FIXME прижать вниз страницы (например на странице эффективности он не снизу) -->
  <div class="mx-auto max-w-3xl px-4 sm:px-6 lg:max-w-7xl lg:px-8">
    <div class="py-8 text-center text-sm text-gray-500 sm:text-left">
      <span class="block sm:inline">
      &copy; 2023 CRM "SWIPE"
      </span>
    </div>
  </div>
</footer>

templates/src/_modal_add_employee.html
{% load static %}

<div id="add-target-modal" tabindex="-1" aria-hidden="true"
     class="fixed top-0 left-0 right-0 z-50 hidden w-auto mx-auto p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full bg-gray-600/40">
  <div class="relative w-full h-full max-w-3xl md:h-auto">
    <!-- Modal content -->
    <div class="relative w-full">
      <div class="px-6 py-6 lg:px-8">
        <h3 class="mb-4 text-center tracking-wide font-medium text-gray-900 bg-gray-200 rounded-lg h-10">
          <div class="flex items-center justify-center h-full">
            Добавление нового сотрудника
          </div>
        </h3>
        <form class="space-y-6" method="post" action="{% url 'users:create_employee' %}">
          {% csrf_token %}
          <div class="flex flex-row w-full">
            <label for="last-name-add"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">
              <div class="flex justify-center items-center h-full">
                Фамилия
              </div>
            </label>
            {{ form.last_name }}
          </div>
          <div class="flex flex-row w-full">
            <label for="first-name-add"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">
              <div class="flex justify-center items-center h-full">
                Имя
              </div>
            </label>
            {{ form.first_name }}
          </div>
          <div class="flex flex-row w-full">
            <label for="patronymic-add"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">
              <div class="flex justify-center items-center h-full">
                Отчество
              </div>
            </label>
            {{ form.patronymic }}
          </div>
          <div class="flex flex-row w-full">
            <label for="position-add"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">
              <div class="flex justify-center items-center h-full">
                Должность
              </div>
            </label>
            {{ form.position }}
          </div>
          <div class="flex flex-row w-full">
            <label for="email-add"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">
              <div class="flex justify-center items-center h-full">
                Электронная почта
              </div>
            </label>
            {{ form.email }}

          </div>
          <div class="flex items-center justify-center">
            <button type="submit"
                    class="flex flex-row items-center justify-center w-5/12 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
              <img class="w-9 mr-2" src="{% static 'img/user_add_light.svg' %}" alt="">
              <span class="font-thin tracking-wide">Добавить сотрудника</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

templates/src/_modal_add_task.html
<div id="add-task-modal" tabindex="-1" aria-hidden="true"
     class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full">
  <div class="relative w-full h-full max-w-4xl md:h-auto">
    <div class="relative bg-black rounded-lg shadow bg-opacity-50">
      <div class="px-6 py-6 lg:px-8">
        <div class="font-normal bg-[#454D56;] rounded-lg text-[#FFFFFF] py-4 text-center">
          Добавление новой задачи
        </div>

        <form class="space-y-6" method="post" enctype="multipart/form-data">
          <div class="relative mt-5">
          {{ task_form.name }}
          <label for="floating_filled"
                 class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-4 z-10 origin-[0] left-2.5 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-4">
            Название задачи
          </label>
        </div>
          <div class="mt-5">
            {{ task_form.description }}
          </div>
          <div class="relative mt-5">

            <label for="floating_filled"
                   class="block mb-2 text-sm font-medium text-white">
              Ответственный
            </label>
            {{ task_form.executor }}
          </div>
          <div class="relative mt-5">
            {{ task_form.deadline }}
            <label for="floating_filled"
                   class="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-4 z-10 origin-[0] left-2.5 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-4">
              Срок сдачи
            </label>
          </div>
          {{ file_form }}
          <button type="submit"
                  class="w-full text-white bg-[#23629F] hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
            Отправить задачу исполнителю
          </button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</div>

templates/src/_modal_change_employee.html
{% extends 'base.html' %}
{% load static %}

{% block flowbite %}{% endblock flowbite %}

{% block title %}Редактирование сотрудников{% endblock title %}


{% block content %}
<div id="editUserModal"
{#     tabindex="-1"#}
{#     aria-hidden="true"#}
     class="fixed top-0 left-0 right-0 z-50 hidden w-auto mx-auto p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full bg-gray-600/40">

  <div class="relative w-full h-full max-w-3xl md:h-auto">
    <!-- Modal content -->

    <div class="relative w-full">
      <div class="px-6 py-6 lg:px-8">
        <h3 class="mb-4 text-center tracking-wide font-medium text-gray-900 bg-gray-200 rounded-lg h-10">
          <div class="flex items-center justify-center h-full">
            Редактирование сотрудника
          </div>
        </h3>
        <form class="space-y-6" action="#">
          <div class="flex flex-row w-full">
            <label for="last-name-edit"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">

              <div class="flex justify-center items-center h-full">
                Фамилия
              </div>
            </label>
            <input type="text" name="last-name-edit" id="last-name-edit"
                   class="bg-gray-200 border border-gray-300 text-gray-900 text-sm text-center rounded-r-lg w-full p-2.5"
                   placeholder="" value="" required>
          </div>
          <div class="flex flex-row w-full">
            <label for="first-name-edit"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">
              <div class="flex justify-center items-center h-full">
                Имя
              </div>
            </label>
            <input type="text" name="first-name-edit" id="first-name-edit"
                   class="bg-gray-200 border border-gray-300 text-gray-900 text-sm text-center rounded-r-lg w-full p-2.5"
                 placeholder="" value="" required>


          </div>
          <div class="flex flex-row w-full">
            <label for="patronymic-edit"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">
              <div class="flex justify-center items-center h-full">
                Отчество
              </div>
            </label>
            <input type="text" name="patronymic-edit" id="patronymic-edit"
                   class="bg-gray-200 border border-gray-300 text-gray-900 text-sm text-center rounded-r-lg w-full p-2.5"
                   placeholder="" value="Николаевич" required>
          </div>
          <div class="flex flex-row w-full">
            <label for="position-edit"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">
              <div class="flex justify-center items-center h-full">
                Должность
              </div>
            </label>
            <input type="text" name="position-edit" id="position-edit"
                   class="bg-gray-200 border border-gray-300 text-gray-900 text-sm text-center rounded-r-lg w-full p-2.5"
                   placeholder="" value="Начальник" required>
          </div>
          <div class="flex flex-row w-full">
            <label for="email-edit"
                   class="text-sm font-medium tracking-wide text-gray-900 bg-gray-200 rounded-l-lg w-5/6 border-r border-r-black">
              <div class="flex justify-center items-center h-full">
                Электронная почта
              </div>
            </label>
            <input type="email" name="email-edit" id="email-edit"
                   class="bg-gray-200 border border-gray-300 text-gray-900 text-sm text-center rounded-r-lg w-full p-2.5"
                   placeholder="" value="" required>

          </div>

          <div class="flex items-center justify-center">
            <button type="submit"
                    class="flex flex-row items-center justify-center w-5/12 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
              <img class="w-9 mr-2" src="img/user_add_light.svg" alt="">
              <span class="font-thin tracking-wide">Сохранить изменения</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/src/_navbar.html
{% load static %}
<nav class="bg-all-header-color font-extrabold tracking-wide">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="flex flex-1 items-center justify-center sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <a href="{% url 'tasks:home' %}">
            <img class="block h-11 w-auto lg:hidden max-w-none" src="{% static 'img/logo.svg' %}" alt="Your Company">
            <img class="hidden h-11 w-auto lg:block max-w-none" src="{% static 'img/logo.svg' %}" alt="Your Company">
          </a>
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            {% url 'tasks:home' as home_url %}
            <a href="{{ home_url }}"
               class="{% if request.path == home_url %}bg-active-button-grad text-white
                      {% else %}text-gray-300 hover:bg-active-button-grad hover:text-white
                      {% endif %}px-3 py-2 rounded-md text-sm font-medium">
              Мои задачи
            </a>
            <!-- FIXME нет "активной" когда на самой странице -->
            {% if user.is_staff %}
              {% with user.groups.get as user_group_name %}
                {% url 'tasks:efficiency' user_group_name as efficiency_url %}
                <a href="{{ efficiency_url }}"
                   class="{% if request.path == efficiency_url %}bg-active-button-grad text-white
                      {% else %}text-gray-300 hover:bg-active-button-grad hover:text-white
                      {% endif %}px-3 py-2 rounded-md text-sm font-medium">
                  Эффективность
                </a>
              {% endwith %}
              <a href="#"
                 class="text-gray-300 hover:bg-active-button-grad hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                Документы
              </a>
            {% endif %}
            {% url 'users:division' as division_url %}
            <a href="{{ division_url }}"
               class="{% if request.path == division_url %}bg-active-button-grad text-white
                      {% else %}text-gray-300 hover:bg-active-button-grad hover:text-white
                      {% endif %}px-3 py-2 rounded-md text-sm font-medium"
               aria-current="page">
              Подразделение
            </a>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button type="button" class="rounded-full bg-all-header-color hover:bg-active-button-grad p-1">
          <img src="{% static 'img/user-profile.svg' %}" width="40" alt="image description">
        </button>
        <!-- Profile dropdown -->
        <div class="relative ml-3 bg-gray-700">
          <a href="{% url 'users:logout' %}">
            <button type="submit"
                    class="bg-indigo-500 group relative flex w-full justify-center rounded-md border
                           border-transparent py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2"
                    style="background-color: #23629F;">
              Выйти
            </button>
          </a>
        </div>
      </div>
    </div>
  </div>
  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pt-2 pb-3">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="{{ home_url }}"
         class="{% if request.path == home_url %}bg-gray-900 text-white
                {% else %}text-gray-300 hover:bg-gray-700 hover:text-white
                {% endif %} block px-3 py-2 rounded-md text-base font-medium" aria-current="page">
        Мои задачи
      </a>
      <a href="{{ efficiency_url }}"
         class="{% if request.path == efficiency_url %}bg-gray-900 text-white
                {% else %}text-gray-300 hover:bg-gray-700 hover:text-white
                {% endif %} block px-3 py-2 rounded-md text-base font-medium">
        Эффективность
      </a>
      <a href="#"
         class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">
        Документы
      </a>
      <a href="{{ division_url }}"
         class="{% if request.path == division_url %}bg-gray-900 text-white
                {% else %}text-gray-300 hover:bg-gray-700 hover:text-white
                {% endif %} block px-3 py-2 rounded-md text-base font-medium">
        Подразделение
      </a>
    </div>
  </div>
</nav>