config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include('users.urls')),
    path('', include('tasks.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path

from .views import *

app_name = 'tasks'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('task/<int:pk>', TaskUpdateView.as_view(), name='update_task'),
    path('efficiency/<str:group_name>', efficiency_view, name='efficiency'),

    path('api/user_tasks/<int:days>/', get_user_tasks, name='user_tasks'),
    path('api/division_tasks/<int:days>/', get_all_division_tasks, name='division_tasks'),
    path('api/task_list/', TaskApiView.as_view(), name='task_api')
]

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block flowbite %}
    <link rel="stylesheet" href="{% static 'flowbite/dist/flowbite.min.css' %}">
  {% endblock %}
  <link rel="stylesheet" href="{% static 'css/dist/output.css' %}">
  <title>{% block title %}CRM "Swipe"{% endblock title %}</title>
  <script src="https://code.jquery.com/jquery-3.6.3.min.js"
          integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  {% block head %}{% endblock head %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body class="bg-body-gradient font-montserrat h-screen">
{% block login %}{% endblock login %}
{% block navbar %}
  {% include 'src/_navbar.html' %}
{% endblock navbar %}

{% block content %}
{% endblock content %}

{% block footer %}
  {% include 'src/_footer.html' %}
{% endblock footer %}

<script src="{% static 'flowbite/dist/flowbite.min.js' %}"></script>
{% block scripts %}
{% endblock scripts %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="mt-5 px-8 sm:px-10 lg:px-32 h-auto">
    <div class="mx-auto">
      <div class="rounded-lg">
        <div class="flex flex-wrap items-center">
          <div class="mr-4 flex">
            <button data-modal-target="add-task-modal" data-modal-toggle="add-task-modal" type="button"
                    class="relative inline-flex items-center rounded-md border border-gray-500 bg-[#23629F] px-4 py-2 text-sm font-medium text-white hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-800 shadow-lg">
              <!-- Heroicon name: mini/plus -->
              <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                   aria-hidden="true">
                <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z">
                </path>
              </svg>
              <span>
                Добавить задачу
              </span>
            </button>
          </div>
          <div class="w-auto flex-auto h-full">
            <div class="relative shadow-lg">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <!-- Heroicon name: mini/magnifying-glass -->
                <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                     fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd"
                        d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z"
                        clip-rule="evenodd"></path>
                </svg>
              </div>
              <input id="search" name="search"
                     class="border border-gray-500 block w-full rounded-md border border-transparent bg-[#eeeeee] py-2 pl-10 pr-3 leading-5 text-gray-300 placeholder-gray-400 focus:border-white focus:bg-white focus:text-gray-900 focus:outline-none focus:ring-white sm:text-sm"
                     placeholder="Поиск" type="search">
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-8 flex flex-col">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 rounded-lg shadow-xl">
            <table class="min-w-full table-fixed">
              <thead class="bg-eee">
              <tr class="divide-x divide-gray-400 shadow-xl">
                <th scope="col" class="px-2 text-center rounded-l-lg">
                  <img src="{% static 'img/icon1.svg' %}" width="32" alt="image description" class="mx-auto max-w-none">
                </th>
                <th scope="col" class="px-2 text-center">
                  <img src="{% static 'img/icon2.svg' %}" width="32" alt="image description" class="mx-auto max-w-none">
                </th>
                <th scope="col" class="px-2 text-center">
                  <img src="{% static 'img/icon4.svg' %}" width="16" alt="image description" class="mx-auto max-w-none">
                </th>
                <th scope="col" class="px-4 py-2 text-center">
                  <div class="font-normal bg-[#454D56B2;] rounded-lg text-[#FFFFFF] py-2">
                    Название задачи
                  </div>
                </th>
                <th scope="col" class="px-2 text-center">
                  <div class="font-normal bg-[#454D56B2;] rounded-lg text-[#FFFFFF] py-2">
                    Время постановки
                  </div>
                </th>
                <th scope="col" class="px-2 text-center">
                  <div class="font-normal bg-[#454D56B2;] rounded-lg text-[#FFFFFF] py-2">
                    Срок выполнения
                  </div>
                </th>
                <th scope="col" class="px-2 text-center">
                  <div class="font-normal bg-[#454D56B2;] rounded-lg text-[#FFFFFF] py-2">
                    Постановщик
                  </div>
                </th>
                <th scope="col" class="px-2 text-center rounded-r-lg">
                  <div class="font-normal bg-[#454D56B2;] rounded-lg text-[#FFFFFF] py-2">
                    Ответственный
                  </div>
                </th>
              </tr>
              </thead>
              <tbody class="bg-eee">
              {% for task in tasks %}
                <tr class="divide-x divide-gray-400 bg-none opacity-100" height="16">
                </tr>
                <tr class="divide-x divide-gray-400 shadow-2xl clickable-row task-table-row"
                    data-href="{% url 'tasks:update_task' task.pk %}">
                  <th scope="col" class="text-center rounded-l-lg">
                    <img src="{% static 'img/icon1.svg' %}" width="32" alt="image description"
                         class="mx-auto max-w-none">
                  </th>
                  <th scope="col" class="text-center">
                    <img src="{% static 'img/icon2.svg' %}" width="32" alt="image description"
                         class="mx-auto max-w-none">
                  </th>
                  <th scope="col" class="text-center">
                    <img src="{% static 'img/button_and_menu.svg' %}" width="32" alt="image description"
                         class="mx-auto max-w-none"
                    >
                  </th>
                  <td class="px-32 py-3 whitespace-nowrap text-center">{{ task.name }}</td>
                  <td class="whitespace-nowrap text-center">{{ task.created_at }}</td>
                  <td class="whitespace-nowrap text-center">{{ task.deadline }}</td>
                  <td class="whitespace-nowrap text-center">
                    {{ task.guarantor.first_name|slice:1 }}.{{ task.guarantor.patronymic|slice:1 }}. {{ task.guarantor.last_name }}
                  </td>
                  {% with executors=task.executor.all %}
                    {% if executors.count > 1 %}
                      <td class="whitespace-nowrap text-center rounded-r-lg">
                        {{ executors.0.first_name|slice:1 }}.{{ executors.0.patronymic|slice:1 }}. {{ executors.0.last_name }}...
                      </td>
                    {% else %}
                      <td class="whitespace-nowrap text-center rounded-r-lg">
                        {{ executors.0.first_name|slice:1 }}.{{ executors.0.patronymic|slice:1 }}. {{ executors.0.last_name }}
                      </td>
                    {% endif %}
                  {% endwith %}
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% include 'src/_modal_add_task.html' %}
{% endblock %}

{% block scripts %}
  <script src="{% static 'js/home.js' %}"></script>
  <script src="{% static 'flowbite/dist/flowbite.min.js' %}"></script>
{% endblock %}