config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include('users.urls')),
    path('', include('tasks.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path

from .views import *

app_name = 'tasks'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('task/<int:pk>', TaskUpdateView.as_view(), name='update_task'),
    path('efficiency/<str:group_name>', efficiency_view, name='efficiency'),

    path('api/user_tasks/<int:days>/', get_user_tasks, name='user_tasks'),
    path('api/division_tasks/<int:days>/', get_all_division_tasks, name='division_tasks'),
    path('api/task_list/', TaskApiView.as_view(), name='task_api')
]

users/urls.py
from django.urls import path, include

from .views import (
    LoginView, DivisionView, PasswordResetView, PasswordResetConfirmView, UpdateEmployeeView, CreateEmployeeView,
    password_change, delete_employee,
)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('password_change/<int:pk>/', password_change, name='password_change'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('', include('django.contrib.auth.urls')),

    path('delete/<int:pk>/', delete_employee, name='delete_employee'),
    path('update/<int:pk>/', UpdateEmployeeView.as_view(), name='update_employee'),
    path('add_employee/', CreateEmployeeView.as_view(), name='create_employee'),
    path('division/', DivisionView.as_view(), name='division'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models

from users.services import generate_password


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        verbose_name='имя пользователя', max_length=150, unique=True,
        validators=[username_validator],
        error_messages={
            "unique": "Пользователь с таким именем пользователя уже существует"
        }
    )
    first_name = models.CharField('имя', max_length=150)
    last_name = models.CharField('фамилия', max_length=150)
    email = models.EmailField(verbose_name='email адрес')
    patronymic = models.CharField(max_length=255, verbose_name='отчество')
    position = models.CharField(max_length=255, verbose_name='должность')

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def change_password(self):
        new_password = generate_password()
        self.set_password(new_password)
        self.save()
        return new_password

users/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import (
    AuthenticationForm as DjangoAuthenticationForm,
    UsernameField,
    SetPasswordForm as DjangoSetPasswordForm
)
from django.forms import TextInput, ModelForm, EmailInput

User = get_user_model()


class AuthenticationForm(DjangoAuthenticationForm):
    username = UsernameField(widget=forms.TextInput(
        attrs={
            'type': 'text',
            'name': 'username',
            'class': 'form-control text-center text-lowercase',
            'placeholder': 'Имя пользователя',
        }
    ))
    password = forms.CharField(
        label='Пароль',
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
                'name': 'password',
                'id': 'password',
                'class': 'form-control text-center text-lowercase',
                'placeholder': 'пароль',
                'autocomplete': 'current-password',
            }),
    )


class UserCreationForm(ModelForm):
    email = forms.EmailField(
        label='Email адрес',
        max_length=254,
        widget=forms.EmailInput(attrs={
            'type': 'email',
            'name': 'email-add',
            'id': 'email-add',
            'class': 'bg-gray-200 border border-gray-300 text-gray-900 text-sm rounded-r-lg w-full p-2.5',
            'placeholder': 'example@email.ru'
        }
        )
    )
    is_staff = forms.BooleanField(
        label='Начальник',
        help_text='',
        required=False
    )

    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'patronymic',
                  'is_staff', 'position', 'email')
        widgets = {
            'first_name': TextInput(attrs={
                'type': 'text',
                'name': 'first-name-add',
                'id': 'first-name-add',
                'placeholder': '',
                'class': 'bg-gray-200 border border-gray-300 text-gray-900 text-sm rounded-r-lg w-full p-2.5'
            }),
            'last_name': TextInput(attrs={
                'type': 'text',
                'name': 'last-name-add',
                'id': 'last-name-add',
                'placeholder': '',
                'class': 'bg-gray-200 border border-gray-300 text-gray-900 text-sm rounded-r-lg w-full p-2.5'
            }),

            'patronymic': TextInput(attrs={
                'type': 'text',
                'name': 'patronymic-add',
                'id': 'patronymic-add',
                'placeholder': '',
                'class': 'bg-gray-200 border border-gray-300 text-gray-900 text-sm rounded-r-lg w-full p-2.5'
            }),
            'position': TextInput(attrs={
                'type': 'text',
                'name': 'position-add',
                'id': 'position-add',
                'placeholder': '',
                'class': 'bg-gray-200 border border-gray-300 text-gray-900 text-sm rounded-r-lg w-full p-2.5'
            }),
        }


class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'patronymic', 'is_staff', 'position', 'email')
        widgets = {
            'last_name': TextInput(attrs={
                'class': 'pl-4 py-2.5 rounded-none rounded-r-lg bg-gray-50 border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
            }),
            'first_name': TextInput(attrs={
                'class': 'pl-4 py-2.5 rounded-none rounded-r-lg bg-gray-50 border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
            }),
            'patronymic': TextInput(attrs={
                'class': 'pl-4 py-2.5 rounded-none rounded-r-lg bg-gray-50 border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
            }),
            'position': TextInput(attrs={
                'class': 'pl-4 py-2.5 rounded-none rounded-r-lg bg-gray-50 border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
            }),
            'is_staff': forms.CheckboxInput(attrs={
                'class': 'w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600'
            }),
            'email': EmailInput(attrs={
                'class': 'pl-4 py-2.5 rounded-none rounded-r-lg bg-gray-50 border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
            }),
        }


class SetPasswordForm(DjangoSetPasswordForm):
    new_password1 = forms.CharField(
        label='Новый пароль',
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'class': 'mx-auto text-center text-gray-900 sm:text-sm block w-[75%] p-2.5'
            }),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label='Подтвердите новый пароль',
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'class': 'mx-auto text-center text-gray-900 sm:text-sm block w-[75%] p-2.5'
            }),
    )

users/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    LoginView as DjangoLoginView,
    PasswordResetView as DjangoPasswordResetView,
    PasswordResetConfirmView as DjangoPasswordResetConfirmView
)
from django.core.exceptions import ObjectDoesNotExist
from django.core.handlers.wsgi import WSGIRequest
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, UpdateView

from .forms import AuthenticationForm, UserCreationForm, SetPasswordForm, UserUpdateForm
from .services.users import create_new_user_and_return_context

from config.settings import EMAIL_HOST_USER, EMAIL_HOST_PASSWORD

User = get_user_model()


class DivisionView(ListView):
    model = User
    template_name = 'users/division_list.html'
    context_object_name = 'employees'

    @method_decorator(login_required(login_url='users:login'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, **kwargs):
        group_id = self.request.user.groups.get().id
        employees = User.objects.filter(groups__id=group_id).order_by('-is_staff').order_by('pk')
        form = UserCreationForm()
        context = {
            'employees': employees,
            'form': form
        }
        return render(request, self.template_name, context)


class CreateEmployeeView(View):
    def post(self, request):
        form = UserCreationForm(request.POST)
        context = {
            'form': form
        }
        if form.is_valid():
            try:
                group = request.user.groups.get()
            except ObjectDoesNotExist:
                return redirect('users:division')
            context = create_new_user_and_return_context(form, group)
            email = form.cleaned_data.get('email')
            password = context.get('password')
            send_mail(subject='СRM_SWIPE_PASSWORD', message=f'Ваш пароль, сохраните его: {password}',
                      recipient_list=[email], from_email=EMAIL_HOST_USER)
            return render(request, 'users/add_employee_done.html', context)
        return render(request, 'users/division_list.html', context)


class UpdateEmployeeView(UpdateView):
    model = User
    template_name = 'users/update_employee.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:division')

    @method_decorator(staff_member_required(login_url='users:login'))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@staff_member_required(login_url='users:login')
def delete_employee(request: WSGIRequest, pk: int):
    user = User.objects.get(pk=pk)
    user.delete()
    return redirect('users:division')


@staff_member_required(login_url='users:login')
def password_change(request: WSGIRequest, pk: int):
    # TODO сделать отправку нового пароля пользователю
    user = User.objects.get(pk=pk)
    new_password = user.change_password()
    context = {
        'password': new_password
    }
    return render(request, 'registration/password_change_complete.html', context)


class LoginView(DjangoLoginView):
    form_class = AuthenticationForm


class PasswordResetView(DjangoPasswordResetView):
    success_url = reverse_lazy('users:password_reset_done')


class PasswordResetConfirmView(DjangoPasswordResetConfirmView):
    form_class = SetPasswordForm
    success_url = reverse_lazy("users:password_reset_complete")

templates/users/add_employee.html
{% extends 'base.html' %}

{% block content %}
  <h1>Добавить сотрудника</h1>
  <hr>
  <form action="{% url 'users:add_employee' %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Добавить</button>
  </form>
{% endblock content %}

templates/users/add_employee_done.html
{% extends 'base.html' %}

{% block content %}
  <p>Новый сотрудник успешно добавлен!</p>
  <p>Имя пользователя и пароль повторены ниже, ОБЯЗАТЕЛЬНО сохраните их (в дальнейшем посмотреть пароль возможности не
    будет), данные так же отправлены сотруднику на электронную почту.</p>
  <hr>
  <p>Имя пользователя: {{ username }}</p>
  <p>Пароль: {{ password }}</p>
  <a href="{% url 'users:division' %}">
    <button type="button">К подразделению</button>
  </a>
{% endblock %}

templates/users/division_list.html
{% extends 'base.html' %}
{% load static %}

{% block flowbite %}{% endblock flowbite %}

{% block title %}Список сотрудников{% endblock title %}

{% block content %}
  <div class="flex items-center justify-between pb-1 m-10">
    <div class="w-1/6 pr-2">
      <button type="button" data-modal-target="add-target-modal" data-modal-toggle="add-target-modal"
              class="relative inline-flex w-full items-center justify-center rounded-lg shadow-lg border border-gray-500 bg-[#23629F] py-1.5 hover:bg-[#0c70d4] focus:outline-none">
        <img class="mr-2 h-12" src="{% static 'img/user_add_light.svg' %}" alt="">
        <span class="font-light tracking-wide text-white text-base">
          Добавить сотрудника
        </span>
      </button>
    </div>
  </div>

  {% include 'src/_modal_add_employee.html' %}

  <div class="mx-64 mt-10 mb-10 overflow-x-auto">
    <table class="w-full text-left text-gray-500">
      <thead class="text-black h-8 bg-white/40">
      <tr class="divide-x">
        <th scope="col" class="p-4 border-r border-r-black text-center rounded-l-3xl">
          №
        </th>
        <th scope="col" class="px-8 py-3 text-center">
          ФИО сотрудника
        </th>
        {% if user.is_staff %}
          <th scope="col" class="px-6 py-3 border-l border-l-black text-center">
            Должность
          </th>
        {% else %}
          <th scope="col" class="px-6 py-3 border-l border-l-black text-center rounded-r-3xl">
            Должность
          </th>
        {% endif %}
        {% if user.is_staff %}
          <th scope="col" class="px-6 py-3 rounded-r-3xl border-l border-l-black">
            <div class="flex items-center justify-center">
              <img src="{% static 'img/filter.svg' %}" alt="" sizes="" srcset="">
            </div>
          </th>
        {% endif %}
      </tr>
      </thead>

      <tbody>
      {% for employee in employees %}
        <tr class="divide-x" height="10">
        </tr>
        <tr
                {% if user.is_staff %}
                  class="bg-white/40 text-black hover:bg-white/20 clickable-row hover:cursor-pointer"
                  data-href="{% url 'users:update_employee' employee.pk %}"
                {% else %}
                  class="bg-white/40 text-black"
                {% endif %}
        >
          <td class="w-4 p-4 border-r border-r-black rounded-l-3xl">
            <div class="text-center">
              {{ forloop.counter }}
            </div>
          </td>
          <th scope="row" class="flex items-center px-8 py-4 text-gray-900">
            <div class="pl-3">
              <div class="text-base font-semibold">
                {{ employee.last_name }} {{ employee.first_name }}
                {{ employee.patronymic }}
              </div>
              {% if employee.email %}
                <div class="font-normal text-gray-500">{{ employee.username }} - {{ employee.email }}</div>
              {% else %}
                <div class="font-normal text-gray-500">{{ employee.username }}</div>
              {% endif %}
            </div>
          </th>
          {% if user.is_staff %}
            <td class="px-6 py-4 border-r border-r-black border-l border-l-black">
              {{ employee.position }}
            </td>
          {% else %}
            <td class="px-6 py-4 border-l border-l-black rounded-r-3xl">
              {{ employee.position }}
            </td>
          {% endif %}
          {% if user.is_staff %}
            <td class="px-6 py-4 rounded-r-3xl">
              <a href="{% url 'users:password_change' employee.pk %}" type="button"
                 class="font-medium text-blue-600 hover:underline flex justify-center">
                <img src="{% static 'img/password_change.svg' %}" alt="" sizes="" srcset="">
              </a>
            </td>
          {% endif %}
        </tr>
        <tr class="divide-x" height="10">
        </tr>
        </tbody>
      {% endfor %}
    </table>
  </div>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

templates/users/update_employee.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="w-full p-4 md:inset-0">
    <div class="relative w-full h-[90vh] flex justify-center items-center">
      <div class="px-6 py-6 lg:px-8 w-[48rem] mx-auto">
        <div class="font-normal bg-[#454D56;] rounded-lg text-[#FFFFFF] py-4 text-center">
          Редактирование сотрудника
        </div>
        <form class="space-y-6" method="post">
          <div class="mt-5 flex">
            <span class="w-1/4 pl-4 text-center inline-flex justify-center items-center px-3 text-sm text-gray-900 bg-gray-200 border border-r-0 border-gray-300 rounded-l-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
              Фамилия
            </span>
            {{ form.last_name }}
          </div>
          <div class="mt-5 flex">
            <span class="w-1/4 text-center inline-flex justify-center items-center px-3 text-sm text-gray-900 bg-gray-200 border border-r-0 border-gray-300 rounded-l-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
              Имя
            </span>
            {{ form.first_name }}
          </div>
          <div class="mt-5 flex">
            <span class="w-1/4 text-center inline-flex justify-center items-center text-sm text-gray-900 bg-gray-200 border border-r-0 border-gray-300 rounded-l-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
              Отчество
            </span>
            {{ form.patronymic }}
          </div>
          <div class="mt-5 flex">
            <span class="w-1/4 text-center inline-flex justify-center items-center px-3 text-sm text-gray-900 bg-gray-200 border border-r-0 border-gray-300 rounded-l-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
              Должность
            </span>
            {{ form.position }}
          </div>
          <div class="mt-5 flex">
            <span class="w-1/4 text-center inline-flex justify-center items-center px-3 text-sm text-gray-900 bg-gray-200 border border-r-0 border-gray-300 rounded-l-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
              Начальник
            </span>
            <span class="pl-4 rounded-none rounded-r-lg bg-gray-50 border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
              {{ form.is_staff }}
            </span>
          </div>
          <div class="mt-5 flex">
            <span class="w-1/4 text-center inline-flex justify-center items-center px-3 text-sm text-gray-900 bg-gray-200 border border-r-0 border-gray-300 rounded-l-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
              Электронная почта
            </span>
            {{ form.email }}
          </div>
          <button type="submit"
                  class="mt-5 py-4 w-full text-white bg-[#23629F] hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
            Сохранить изменения
          </button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}